// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0RBreYkHWXbnOgKl-qGmQ0mRhBO0M_Qk',
    appId: '1:991956612851:web:cd2820c0ce377bbd4b2986',
    messagingSenderId: '991956612851',
    projectId: 'aniemamobileapp',
    authDomain: 'aniemamobileapp.firebaseapp.com',
    storageBucket: 'aniemamobileapp.firebasestorage.app',
    measurementId: 'G-ZWL4DPFRGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-cy8p46MwuJcWQUyDvyGy9EFQL0q_BDQ',
    appId: '1:883493509933:android:571ef526b30e51db1791a4',
    messagingSenderId: '883493509933',
    projectId: 'arsitekbro-57199',
    storageBucket: 'arsitekbro-57199.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXfnl-IU_HdQ5Qbb2aVnUt7y6qb2N8FPs',
    appId: '1:991956612851:ios:b5960d272b656f2c4b2986',
    messagingSenderId: '991956612851',
    projectId: 'aniemamobileapp',
    storageBucket: 'aniemamobileapp.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXfnl-IU_HdQ5Qbb2aVnUt7y6qb2N8FPs',
    appId: '1:991956612851:ios:b5960d272b656f2c4b2986',
    messagingSenderId: '991956612851',
    projectId: 'aniemamobileapp',
    storageBucket: 'aniemamobileapp.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0RBreYkHWXbnOgKl-qGmQ0mRhBO0M_Qk',
    appId: '1:991956612851:web:823c27d7fe9e0f414b2986',
    messagingSenderId: '991956612851',
    projectId: 'aniemamobileapp',
    authDomain: 'aniemamobileapp.firebaseapp.com',
    storageBucket: 'aniemamobileapp.firebasestorage.app',
    measurementId: 'G-8D0F17RLCE',
  );
}